import "./globals.css";
import { Inter } from "next/font/google";
import NavBar from "@/components/navbar/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-slate-800">
        <NavBar />
        <div className="mt-[92px]">{children}</div>
      </body>
    </html>
  );
}
